---
  - name: Install bitlbee package
    apt: pkg=bitlbee state=installed

  - name: Create bitlbee config directory
    file: path=/etc/bitlbee state=directory owner=root group=root mode=0755

  - name: Create bitlbee state directory
    file: path=/var/run/bitlbee state=directory owner=bitlbee group=bitlbee mode=0700

  - name: Install bitlbee config file
    template: src=bitlbee-conf.j2 dest=/etc/bitlbee/bitlbee.conf owner=root group=root mode=0644
    notify: restart bitlbee

  - name: Install /etc/defaults/bitlbee file
    template: src=bitlbee.default dest=/etc/default/bitlbee owner=root group=root mode=0644
    notify: restart bitlbee

  - name: Install bitlbee MOTD file
    copy: src=bitlbee-motd.txt dest=/etc/bitlbee/motd.txt owner=root group=root mode=0644
    notify: restart bitlbee

  - name: Configure bitlbee IM accounts
    notify: stop bitlbee
    template: src=user-conf.j2 dest=/var/lib/bitlbee/reed.xml owner=bitlbee group=bitlbee mode=0600
    notify: start bitlbee

  - name: Run bitlbee service
    service: name=bitlbee enabled=yes state=started

